"""Generate the two rarity-probe training configs from configs/train.yaml.

The two arms MUST differ in exactly one knob (`training.intensity_window.full_dim_bias`)
or the experiment is uninterpretable. Generating them from a single source instead of
hand-copying two YAML files is what guarantees that -- and this script ASSERTS it before
writing, so a future edit to train.yaml cannot silently introduce a second difference.

    python scripts/make_probe_configs.py

Writes configs/train_probe_A_status_quo.yaml (dim_bias 1.6, the shipped sampler)
   and configs/train_probe_B_flat.yaml       (dim_bias 1.0, log-uniform in log A1).
"""
from __future__ import annotations

import copy
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from spotpipe.paths import get_paths  # noqa: E402

STEPS = 8000                # ~1/5 of the full 40k run: a diagnostic, not a headline model
RAMP = 4000                 # reach full curriculum difficulty by the halfway point
ARMS = (("A_status_quo", 1.6), ("B_flat", 1.0))

HEADER = """# AUTO-GENERATED by scripts/make_probe_configs.py -- do not hand-edit.
# Regenerate with: python scripts/make_probe_configs.py
#
# RARITY-HYPOTHESIS PROBE, arm {arm}.   full_dim_bias = {bias}
#
# The two arms are IDENTICAL except for `training.intensity_window.full_dim_bias`. That IS
# the experiment: if the intensity head's bright-end collapse is caused by the dim-biased
# sampler (only ~5% of trained spots exceed ~1,000 photons), then flattening the sampler to
# log-uniform (dim_bias = 1.0) should shrink the bright+dense bias. If it does not move,
# rarity is refuted too and the cause is in the loss/head.
#
# Background: docs/coverage_probe_findings.md (the COVERAGE explanation is already dead --
# brightness and density are drawn independently; corr = +0.02).
#
# Short schedule ({steps} steps, curriculum ramp {ramp}). NOTHING trained from this config
# may be shipped as a checkpoint.
#
# Read out with:
#   python scripts/bright_dense_probe.py --checkpoint <run-dir> --device cuda
"""


def flatten(d: dict, prefix: str = "") -> dict:
    out = {}
    for k, v in d.items():
        if isinstance(v, dict):
            out.update(flatten(v, f"{prefix}{k}."))
        else:
            out[f"{prefix}{k}"] = v
    return out


def main() -> int:
    configs = get_paths().configs
    base = yaml.safe_load(open(configs / "train.yaml", encoding="utf-8"))

    base["training"]["train_steps"] = STEPS
    base["training"]["lr_warmup_steps"] = 300
    base["training"]["variance_warmup_steps"] = 800
    base["training"]["curriculum"]["curriculum_ramp_steps"] = RAMP
    base["training"]["eval_every"] = 500
    base["training"]["checkpoint_every"] = 1000

    written = {}
    for arm, bias in ARMS:
        cfg = copy.deepcopy(base)
        cfg["training"]["intensity_window"]["full_dim_bias"] = bias
        cfg["experiment"] = {
            "name": f"rarity-probe-{arm}",
            "note": (f"Rarity-hypothesis probe, arm {arm}: full_dim_bias={bias}. "
                     f"Diagnostic only ({STEPS} steps). Tests whether the dim-biased "
                     f"intensity sampler causes the bright+dense intensity-head collapse. "
                     f"See docs/coverage_probe_findings.md."),
        }
        path = configs / f"train_probe_{arm}.yaml"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(arm=arm, bias=bias, steps=STEPS, ramp=RAMP))
            yaml.safe_dump(cfg, fh, sort_keys=False, default_flow_style=False, width=100)
        written[arm] = cfg
        print(f"wrote {path.name}: full_dim_bias={bias}")

    # The whole experiment rests on this: exactly ONE substantive difference.
    fa = flatten(written["A_status_quo"])
    fb = flatten(written["B_flat"])
    diff = {k for k in set(fa) | set(fb)
            if fa.get(k) != fb.get(k) and not k.startswith("experiment.")}
    expected = {"training.intensity_window.full_dim_bias"}
    if diff != expected:
        print(f"\nFATAL: arms differ in {sorted(diff)}, expected only {sorted(expected)}")
        return 1
    print(f"\nverified: the arms differ in exactly one knob -> {sorted(expected)[0]} "
          f"({ARMS[0][1]} vs {ARMS[1][1]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
