"""Generate the two FULL 40k head-fix configs from configs/train.yaml.

Unlike scripts/make_delta_configs.py (which shortens the schedule to 8k for a cheap
diagnostic), this keeps train.yaml's FULL production schedule and changes ONLY
`model.head_parameterisation`. The two arms are the real retrain candidates:

  train_40k_INDEP.yaml  -- independent head (the proven architecture; hrnet_large_measured
                           reached alpha-MAE 0.036 / null +0.021 at 40k on the OLD density
                           range -- this re-trains it on the v3-covering density 0.030).
  train_40k_DELTA.yaml  -- (logI1, delta) head (cleaner alpha=0 null at matched 8k steps;
                           fixes the bright+dense intensity shrinkage). Upside bet.

WHY BOTH: a 40k retrain is required regardless of head, because hrnet_large_measured was
trained at density max 0.012 and is OUT-OF-DISTRIBUTION in the v3 benchmark's crowded cells
(up to 0.025) -- exactly where the win over the baselines lives. So the previous model
cannot be the v3 headline. Run both, read out with alpha_probe + bright_dense_probe on the
run-dirs, and let the full v3 evaluation vs baselines (alpha=0 null gated FIRST) pick.

    python scripts/make_40k_headfix_configs.py
"""
from __future__ import annotations

import copy
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from spotpipe.paths import get_paths  # noqa: E402

ARMS = (("INDEP", "independent"), ("DELTA", "delta"))

HEADER = """# AUTO-GENERATED by scripts/make_40k_headfix_configs.py -- do not hand-edit.
# Regenerate: python scripts/make_40k_headfix_configs.py
#
# FULL 40k head-fix candidate, arm {arm}.   model.head_parameterisation = {mode}
#
# Identical to configs/train.yaml (the v3-covering distribution: density max 0.030,
# max_spots 3000) EXCEPT model.head_parameterisation. This is a real production retrain,
# not a diagnostic -- the winner becomes the headline checkpoint.
#
# Decision rationale + the 8k evidence: docs/intensity_head_fix_proposal.md,
# docs/shrinkage_probe_findings.md, results/alpha_{{INDEP,DELTA}}.csv.
#
# After training, read out on the RUN DIR (accepts a path, no install needed):
#   python scripts/alpha_probe.py        --checkpoint outputs/train/headfix40k-{arm} --device cuda
#   python scripts/bright_dense_probe.py --checkpoint outputs/train/headfix40k-{arm} --device cuda
"""


def flatten(d, p=""):
    out = {}
    for k, v in d.items():
        out.update(flatten(v, f"{p}{k}.")) if isinstance(v, dict) else out.__setitem__(f"{p}{k}", v)
    return out


def main() -> int:
    configs = get_paths().configs
    base = yaml.safe_load(open(configs / "train.yaml", encoding="utf-8"))

    # sanity: confirm we are building on the v3-covering distribution, not a stale train.yaml
    dmax = float(base["simulator"]["scene"]["density"]["max"])
    steps = int(base["training"]["train_steps"])
    if dmax < 0.03 - 1e-9:
        print(f"REFUSING: train.yaml density max is {dmax}, expected >= 0.030 (v3 coverage). "
              f"Fix configs/train.yaml first.")
        return 1
    if steps < 40000:
        print(f"WARNING: train.yaml train_steps is {steps}, not the full 40000.")

    written = {}
    for arm, mode in ARMS:
        cfg = copy.deepcopy(base)
        cfg.setdefault("model", {})["head_parameterisation"] = mode
        cfg["experiment"] = {
            "name": f"headfix40k-{arm}",
            "note": (f"Full 40k head-fix candidate, arm {arm}: head_parameterisation={mode}, "
                     f"v3-covering distribution (density max {dmax}). The winner becomes the "
                     f"headline checkpoint. See docs/intensity_head_fix_proposal.md."),
        }
        path = configs / f"train_40k_{arm}.yaml"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(arm=arm, mode=mode))
            yaml.safe_dump(cfg, fh, sort_keys=False, default_flow_style=False, width=100)
        written[arm] = cfg
        print(f"wrote {path.name}: head_parameterisation={mode}  steps={steps}  density_max={dmax}")

    fa, fb = flatten(written["INDEP"]), flatten(written["DELTA"])
    diff = {k for k in set(fa) | set(fb)
            if fa.get(k) != fb.get(k) and not k.startswith("experiment.")}
    if diff != {"model.head_parameterisation"}:
        print(f"\nFATAL: arms differ in {sorted(diff)}, expected only model.head_parameterisation")
        return 1
    print("\nverified: the two 40k arms differ in exactly one knob (head_parameterisation).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
