"""Generate the two intensity-head bake-off configs from configs/train.yaml.

The bake-off tests whether the (logI1, delta) reparameterisation fixes the
protein-channel-under-crowding shrinkage (docs/shrinkage_probe_findings.md). Two
8k-step arms differing in EXACTLY one knob -- `model.head_parameterisation` -- so any
difference in the readout is attributable to the reparameterisation and nothing else.
This script ASSERTS the single-knob difference before writing.

    python scripts/make_delta_configs.py

Writes configs/train_headfix_INDEP.yaml (independent -- the control at matched steps)
   and configs/train_headfix_DELTA.yaml (the fix).

Note the INDEP control is trained fresh at 8k on the CURRENT config (density max 0.030,
etc.), so it is a matched-steps, matched-distribution baseline. Do NOT compare DELTA to
the 40k hrnet_large_measured -- that confounds the reparameterisation with 5x more steps.
"""
from __future__ import annotations

import copy
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from spotpipe.paths import get_paths  # noqa: E402

STEPS = 8000
RAMP = 4000
ARMS = (("INDEP", "independent"), ("DELTA", "delta"))

HEADER = """# AUTO-GENERATED by scripts/make_delta_configs.py -- do not hand-edit.
# Regenerate with: python scripts/make_delta_configs.py
#
# INTENSITY-HEAD BAKE-OFF, arm {arm}.   model.head_parameterisation = {mode}
#
# The two arms are IDENTICAL except for `model.head_parameterisation`. That IS the
# experiment. Motivation + diagnosis: docs/shrinkage_probe_findings.md and
# docs/intensity_head_fix_proposal.md. The state_dict is identical between modes, so
# both arms have the same parameter count; only the interpretation of the two
# intensity output channels differs (independent: logI1,logI2; delta: logI1,delta).
#
# Short schedule ({steps} steps, curriculum ramp {ramp}). Diagnostic, not a headline.
#
# Read out with (compare the arms to EACH OTHER, never to the 40k model):
#   python scripts/bright_dense_probe.py --checkpoint <run-dir> --device cuda
#   python scripts/shrinkage_probe.py    --checkpoint <run-dir>
"""


def flatten(d: dict, prefix: str = "") -> dict:
    out = {}
    for k, v in d.items():
        if isinstance(v, dict):
            out.update(flatten(v, f"{prefix}{k}."))
        else:
            out[f"{prefix}{k}"] = v
    return out


def main() -> int:
    configs = get_paths().configs
    base = yaml.safe_load(open(configs / "train.yaml", encoding="utf-8"))

    base["training"]["train_steps"] = STEPS
    base["training"]["lr_warmup_steps"] = 300
    base["training"]["variance_warmup_steps"] = 800
    base["training"]["curriculum"]["curriculum_ramp_steps"] = RAMP
    base["training"]["eval_every"] = 500
    base["training"]["checkpoint_every"] = 1000

    written = {}
    for arm, mode in ARMS:
        cfg = copy.deepcopy(base)
        cfg.setdefault("model", {})["head_parameterisation"] = mode
        cfg["experiment"] = {
            "name": f"headfix-{arm}",
            "note": (f"Intensity-head bake-off, arm {arm}: head_parameterisation={mode}. "
                     f"Diagnostic only ({STEPS} steps). Tests the (logI1, delta) fix for the "
                     f"protein-under-crowding shrinkage. See docs/intensity_head_fix_proposal.md."),
        }
        path = configs / f"train_headfix_{arm}.yaml"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(arm=arm, mode=mode, steps=STEPS, ramp=RAMP))
            yaml.safe_dump(cfg, fh, sort_keys=False, default_flow_style=False, width=100)
        written[arm] = cfg
        print(f"wrote {path.name}: head_parameterisation={mode}")

    fa, fb = flatten(written["INDEP"]), flatten(written["DELTA"])
    diff = {k for k in set(fa) | set(fb)
            if fa.get(k) != fb.get(k) and not k.startswith("experiment.")}
    expected = {"model.head_parameterisation"}
    if diff != expected:
        print(f"\nFATAL: arms differ in {sorted(diff)}, expected only {sorted(expected)}")
        return 1
    print(f"\nverified: arms differ in exactly one knob -> model.head_parameterisation "
          f"(independent vs delta)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
